### PR TITLE
Support for manual schema declaration

### LINKED ISSUE #133: Unexpected behavior when importing  a schema
Hello!
I'm using your awesome library to split my server-sice (NodeJS & TypeScript) code.
Unfortunately I faced an issue with import.

I have this .graphql file:

```
type Query {
    users: String
}

type AuthMutation {
    authenticate(code: String!, accountId: String): String
}

schema {
    query: Query,
    mutation: AuthMutation
}
```

And I'm trying to import it in this way: 

```js
import { importSchema } from 'graphql-import';
import * as path from 'path';

const AuthSchema = importSchema(path.join(__dirname, './auth.graphql'));
```

But I'm getting an incorrect result: 

```
type Query {
    users: String
}

type AuthMutation {
    authenticate(code: String!, accountId: String): String
}
```

No schema. Any suggestions on this?

Thank you!

### PR DESCRIPTION
**Pull request by lfades**
Fixes #133 

This PR adds support for the following graphql code:

```gql
schema {
  query: Query
  mutation: Mutation
}
```

The schema above had no effect before and was not included in the resulting graphql schema, with this PR it will be included alongside with type validations for its fields, so if `Query` or `Mutation` are not defined an error is thrown.

Support for a custom name for `query`, `mutation` and `subscription` is also included, so the following schema should work too:

```gql
schema {
  query: A
  mutation: B
  subscription: C
}

# Query
type A {
  users: [User]
}

# Mutation
type B {
  updateUser(name: String!): User
}

# Subscription
type C {
  updateUser(name: String!): User
}
```

Although I don't recommend the above example to anyone, is now possible! but keep in mind that currently if your schema has a type for `Query` / `Mutation` / `Subscription` they'll be included even if they're not used, such behaviour can be easily fixed but I'm not sure if that's even necessary 💃

### CODE REVIEW

**Comment by lfades** [comment]
@schickling this PR is ready, I reverted the changes I brought from my other PR (my bad)

**Comment by lfades** [comment]
@schickling Can you take a look to this PR again please ? thank you 🙏

**Comment by mtodor** [comment]
I've experienced one problem and this PR solves it.

I want to add schema validation for one project and want to use `graphql-cli` for fetching schema and keeping it in the repo for checking endpoint schema changes. And I planned to use `graphql diff` for that, where schema stored in a file will be compared against endpoint schema.

Problem is that I can't change endpoint schema and schema starts like this:
```
schema {
  query: QueryRoot
}
```
and it's saved like that in a file, but when the file is loaded for comparison `importSchema` simply removes `schema` part and comparison always fails because schema from endpoint contains it. :tired_face:

I tried with changes provided with this PR and it worked.

Can we somehow push this forward?

**Comment by ardatan** [comment]
Thank you for this great contribution!!! @lfades
We moved the most of internal logic into GraphQL Toolkit so in GraphQL Toolkit we respect `SchemaDefinition` in the same approach of yours :)
https://github.com/ardatan/graphql-toolkit/blob/35d64e24a0440ceb18c4c2b4090492d0e40f9e90/packages/core/src/import-parser/index.ts#L259

In 1.0.0 beta release, we introduced a lot of changes including this one;
You can install graphql-import@beta to try new changes? Don't forget to modify your code regarding to the migration notes in README.
https://github.com/ardatan/graphql-import#updating-from-07x

**Comment by lfades** [comment]
@ardatan Nice ❤️

**Pull request closed without merging**
